### ISSUE TITLE
Sprint 4:  Enabler - kind status

### ISSUE THREAD

**Issue by teodora-aleksovska** [keitaroinc/enabler#67]
This command _enabler kind status --kube-context keitaro_ doesn't work properly.

After running  enabler kind status --kube-context temp i got the error below:

teodora@teodora-ThinkPad-T16-Gen-1:~/Project/enabler$ enabler kind status --kube-context temp
Traceback (most recent call last):
  File "/home/teodora/.local/bin/enabler", line 11, in <module>
    load_entry_point('enabler', 'console_scripts', 'enabler')()
  File "/home/teodora/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/teodora/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/teodora/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/teodora/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/teodora/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/teodora/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/teodora/.local/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/teodora/.local/lib/python3.10/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/teodora/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: status() got multiple values for argument 'kube_context'

**Comment by JasminaPN** [comment]
Closing since we are moving to Plane Task Board.
